name: Cleanup Artifacts

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Delete all packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: '*' # удалит все пакеты
          package-type: 'container' # или 'maven', если используешь Maven
          min-versions-to-keep: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Delete all tags
        run: |
          git tag | while read tag; do
            git push origin :refs/tags/$tag
          done

      - name: Delete all releases
        run: |
          gh release list | awk '{print $1}' | while read release; do
            gh release delete "$release" -y
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
