name: Cleanup Packages, Tags and Releases

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Delete all packages
        run: |
          gh api user/packages --paginate -q '.[].name' | while read package; do
            echo "Deleting package: $package"
            gh api -X DELETE /user/packages/maven/$package
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Delete all git tags
        run: |
          git tag | while read tag; do
            echo "Deleting tag: $tag"
            git push origin :refs/tags/$tag
          done

      - name: Delete all releases
        run: |
          gh release list -L 1000 | awk '{print $1}' | while read release; do
            echo "Deleting release: $release"
            gh release delete "$release" -y
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
