name: Trigger Clean and Publish Workflows

on:
  push:
    branches:
      - main
jobs:
  trigger-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger clean_up.yml workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/clean_up.yml/dispatches \
            -d '{"ref":"main"}'
  
  trigger-publish:
    runs-on: ubuntu-latest
    needs: trigger-cleanup
    steps:
      - name: Trigger publish-all.yml workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-all.yml/dispatches \
            -d '{"ref":"main"}'
